trigger:
- main

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'
  Buildconfiguration: 'Release'

stages:
- stage: Build
  displayName: Build
  jobs:  
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '6.x'
